version: "3.9"

services:
  web:
    image: email_notification_microservice
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/mircroservice
    ports:
      - 8000:8000
