version: "3.9"

services:
  web:
    image: email_notification_microservice
    build: .
    command: sh ./start_server.sh
    volumes:
      - static_volume:/microservice/static
      - media_volume:/microservice/media
    ports:
      - ${PORT:-80}:${PORT:-80}
    restart: always

volumes:
  static_volume:
  media_volume:
